### ISSUE TITLE
Water Quality Tab - Trend Graph Bug

### ISSUE THREAD

**Issue by nharris-HEC** [HerreraEnvironmental/23-08082-000-TC-WQ-Dashboard#14]
Under the Water Quality Trends tab I noticed that when multiple sites are selected, the user can remove points for a particular site by clicking on the corresponding SITE_CODE in the legend. This, however, does not update the above trend graph as well

**Comment by R-Lionheart** [comment]
@clarkbar88 and @R-Lionheart both ran this error and found there was no problem with downloading any or all data. Issue will be closed.

**Comment by R-Lionheart** [comment]
New bug here: The plot section of this tab has disappeared entirely and I'm also getting an error with some parameter selections. Is anyone else running into this? I am running the most updated version.

**Comment by clarkbar88** [comment]
OH yeah. That's on me. I want to replace the trends charts with a map of the trend directions.

**Comment by R-Lionheart** [comment]
sounds good! I'll leave this issue alone for a little bit then
