### ISSUE TITLE
Water Quality Criteria Tab - Threshold Color Scheme 

### ISSUE THREAD

**Issue by nharris-HEC** [HerreraEnvironmental/23-08082-000-TC-WQ-Dashboard#15]
On the Summary of Water Quality Criteria tab, I am not sure what the threshold is for determining red and green points. Number of violations across all parameters? 
- It would be interesting to see which sites show a trend of decreasing # of violations over time and which show a trend of increasing. 
- It would also be nice to be able to filter by parameter here. The point color could change based on whether or not they currently meet the WQ standard/ meet a threshold for # of violations (however we are symbolizing).

**Comment by clarkbar88** [comment]
Should add legend. (Red = Exceeds at least one water quality criterion)

Highlight:

**Violations**
* Dissolved Oxygen (4 of 10 samples)
* E. coli in Fall

**No Violations**
* pH (0 of 12 samples)
* Temperature (0 of 10 samples)

**Not Measured**
* Fecal Coliform
