### ISSUE TITLE
Water Quality Trends Tab - Map Linking Issue?

### ISSUE THREAD

**Issue by nharris-HEC** [HerreraEnvironmental/23-08082-000-TC-WQ-Dashboard#16]
The only tab without a map or that is not listed as a clickable tab under “Click to do the following” is the “Water Quality Trends Tab”. The title of this tab seems to confuse it with “Data Visualization and Trends” and makes it get lost a little more on the page.

**Comment by clarkbar88** [comment]
Rename to "Summary of Water Quality Trends"
@nharris-HEC - can we unlink the site selection for this tab from the Map?

Should I just convert the barplot to a map?
