### ISSUE TITLE
WQI Tab - Top Graph Legend

### ISSUE THREAD

**Issue by nharris-HEC** [HerreraEnvironmental/23-08082-000-TC-WQ-Dashboard#21]
Under the WQI tab I noticed that the WQI line on the month x WQI graph (top one) isn’t included in the legend. It’s something that I’ll easily be able to know from now on, but could be added to the legend for clarity.

**Comment by clarkbar88** [comment]
use same legend developed for #29  ?

**Comment by R-Lionheart** [comment]
I noticed the default shortParmName for the WQI line is just "black" (I assume that's the line we're talking about as it's the only one not included in the legend), while all the other parameters have their name: "sediment", "temp", "pH", etc. It's unclear where the WQI line actually coming from, I don't see it in the original monthly_wqi_by_parameter.RDS object, where it looks like everything else is coming from. If we can isolate where the data is being drawn from it should be easiest to just modify the original .rds file so plotly adds it to the legend automatically.

**Comment by clarkbar88** [comment]
The Monthly WQI summary score (the black line) is coming from 'monthly_wqi.RDS' seperate from 'monthly_wqi_by_parameter'

We need to add a "monthly_wqi" argument to the monthly_wqi_plot() function. Then, we can do a bind_rows with a filter of both monthly_wqi and monthly_wqi_by_parameter.
Just would need to add "Monthly Summary Score" as the parm name for monthly_wqi

Alternatively, we can modify the WQI script in 'WQI_function.R' to include the summary score along with the parameter scores to bind_rows with monthly_wqi.

I think I prefer the latter approach.

**Comment by R-Lionheart** [comment]
Two things: In the server script, the monthly_wqi variable (line 46) is imported but never used. Second, I notice that monthly_WQI.RDS and monhly_WQI_by_parameter.RDS look like they are relational. Would it be too slow to just rbind them within the data_prep.R script?

**Comment by nharris-HEC** [comment]
Addressed in pull request for **tab_fixes**
