### ISSUE TITLE
Hyperlinks in Map Pop-up

### ISSUE THREAD

**Issue by nharris-HEC** [HerreraEnvironmental/23-08082-000-TC-WQ-Dashboard#26]
- Listed hyperlinks underneath “Click to do the following:” when clicking on a site on the “Map” tab do not visually appear to be hyperlinks. It would be more intuitive to click on them if they were underlined, bolded, or in a slightly different color.
- Those hyperlinks also do not have the same titles as the tabs that they reroute to up at top. I understand that the difference might be to provide greater description of the tabs, but I found it more confusing.

**Comment by clarkbar88** [comment]
If we're not able to force a hyperlink, just add an underline style.
