### ISSUE TITLE
Increase Tab Font Size

### ISSUE THREAD

**Issue by nharris-HEC** [HerreraEnvironmental/23-08082-000-TC-WQ-Dashboard#27]
The tabs at the top do not stand out super well, it might help to increase font size.

**Comment by clarkbar88** [comment]
Or we can try a different interface. Maybe left-side navbar?

**Comment by R-Lionheart** [comment]
I think increasing the font size requires involving css, which I don't know much about. Is it more likely that we'd switch a sidebar, before I start looking into css modifications?

**Comment by R-Lionheart** [comment]
After today's Dashboard meeting where we discussed css, I think that's where we're at with this particular issue (don't think we can change the font/size without using css).
The only adjustment I could make to the tabs was changing the bs_theme version number, which adjusts the overall style of the tabs but doesn't really make them any easier to read. 
I'm going to leave this issue for now until we make a graphics decision.
