### ISSUE TITLE
Increase Sharpness of Colors in Data Visualization and Trends

### ISSUE THREAD

**Issue by nharris-HEC** [HerreraEnvironmental/23-08082-000-TC-WQ-Dashboard#28]
The sharpness of colors of “Data Visualization and Trends”

**Comment by clarkbar88** [comment]
What does this mean?

**Comment by R-Lionheart** [comment]
I think this also falls under the purview of css/aesthetic modifications. I think this issue can be left for now depending on what we decide to do with layouts.
