### ISSUE TITLE
Units on Graphs

### ISSUE THREAD

**Issue by nharris-HEC** [HerreraEnvironmental/23-08082-000-TC-WQ-Dashboard#32]
Units on graphs in “Water Quality Trends”, “WQI”,  “Data Visualization and Trends”, if images are ever used externally.

**Comment by R-Lionheart** [comment]
Just a thought on this, if we're pressed for time an easier fix might be to adjust the raw data to paste the "C" for Celsius into the parameter column itself on the input data, that would save needing to figure out how to paste the C to each number on the graph rendering.
