### ISSUE TITLE
WQC Graph not appearing

### ISSUE THREAD

**Issue by nharris-HEC** [HerreraEnvironmental/23-08082-000-TC-WQ-Dashboard#63]
WQC graph does not appear. Showing error `object 'nViolation' not found` in console

**Comment by nharris-HEC** [comment]
nViolation is caused due to missing data for WQC calcs. Add in warning/error for limited datasets. Graph will not appear when one of the following are missing:
-Temp
-DO
-pH
-E. Coli
-Fecal

**Comment by R-Lionheart** [comment]
I can't get this one to work at all, as in there are currently no scenarios where the map is appearing. So it's not really an issue of missing data so much as no data. I think we should return to this one and review the steps together so we can see where things are going wrong.

**Comment by R-Lionheart** [comment]
Add in:
- Same warning for missing data as the WQI
